server:
    port: 8058
    servlet:
      context-path: /

sa-token:
  # token名称 (同时也是cookie名称)
  token-name: sa-token
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://root:ZyV8fmPGaAzM6DDyHBuh@containers-us-west-12.railway.app:5638/railway?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: ZyV8fmPGaAzM6DDyHBuh
    hikari:
        connection-timeout: 30000
        maximum-pool-size: 15
        minimum-idle: 5
        idle-timeout: 30000
        max-lifetime: 30000
        pool-name: hikariCP

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
#    tags-sorter: alpha
#    operations-sorter: alpha
#    show-extensions: true
#  api-docs:
#    path: /v3/api-docs
#  group-configs:
#    - group: 'default'
#      paths-to-match: '/test/**'
#      packages-to-scan: com.xiaominfo.knife4j.demo.web
#  default-flat-param-object: false
#knife4j:
#  enable: true
#  setting:
#    language: zh_cn
#    swagger-model-name: 实体类列表
#  documents:
#    - name: 标题1
#      locations: classpath:markdown/*
#      group: default
#    - name: 标题2
#      locations: classpath:markdown1/*
#      group: 用户模块
#  basic:
#    enable: false
#    username: zhangsan
#    password: lisi
