server:
  port: 8058
  servlet:
    context-path: /

minio:
  endpoint: yourendpoint
  accessKey: youraccessKey
  secretKey: yoursecretKey

sa-token:
  # token名称 (同时也是cookie名称)
  token-name: sa-token
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false
  is-print: false
  jwt-secret-key: yourkey
  token-prefix: Bearer

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://yourusername:yourpassword@yourhost:yourpost/yourdatabase?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: yourusername
    password: yourpassword
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariCP
      max-life-time: 30000
      connection-timeout: 30000

    